#!/bin/bash
sleep 15
RANGER_HOST=$(hostname -f)
echo "Creating a Ranger Policy for raj_ops"
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/api/policy -d '{"policyName":"Policy for raj_ops","databases":"foodmart","tables":"*","columns":"*","udfs":"","description":"Hive Policy","repositoryName":"Sandbox_hive","repositoryType":"hive","tableType":"Inclusion","columnType":"Inclusion","isEnabled":"true","isAuditEnabled":"true","permMapList":[{"userList":["raj_ops"],"permList":["All"]}]}'
echo "Updating a sample Hive Ranger policy for holger_gov"
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_hive/policy/Policy%20for%20raj_ops -d '{"isEnabled":true,"service":"Sandbox_hive","name":"Policy for raj_ops,holger_gov","description":"","isAuditEnabled":true,"resources":{"column":{"values":["*"],"isExcludes":false,"isRecursive":false},"table":{"values":["*"],"isExcludes":false,"isRecursive":false},"database":{"values":["foodmart"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"all","isAllowed":true}],"users":["raj_ops"],"groups":[],"conditions":[],"delegateAdmin":false},{"accesses":[{"type":"select","isAllowed":true},{"type":"create","isAllowed":true},{"type":"drop","isAllowed":true}],"users":["holger_gov"],"groups":[],"conditions":[],"delegateAdmin":false}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
echo "Updating Atlas Ranger policies for holger_gov"
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_atlas/policy/all%20-%20term -d '{"isEnabled":true,"service":"Sandbox_atlas","name":"all - term","isAuditEnabled":true,"description":"Policy for all - term","resources":{"term":{"values":["*"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"read","isAllowed":true},{"type":"create","isAllowed":true},{"type":"update","isAllowed":true},{"type":"delete","isAllowed":true},{"type":"all","isAllowed":true}],"users":["atlas","admin","ambari-qa","holger_gov"],"groups":[],"conditions":[],"delegateAdmin":true}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_atlas/policy/all%20-%20entity -d '{"isEnabled":true,"service":"Sandbox_atlas","name":"all - entity","isAuditEnabled":true,"description":"Policy for all - entity","resources":{"entity":{"values":["*"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"read","isAllowed":true},{"type":"create","isAllowed":true},{"type":"update","isAllowed":true},{"type":"delete","isAllowed":true},{"type":"all","isAllowed":true}],"users":["atlas","admin","ambari-qa","holger_gov"],"groups":[],"conditions":[],"delegateAdmin":true}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_atlas/policy/all%20-%20type -d '{"isEnabled":true,"service":"Sandbox_atlas","name":"all - type","isAuditEnabled":true,"description":"Policy for all - type","resources":{"type":{"values":["*"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"read","isAllowed":true},{"type":"create","isAllowed":true},{"type":"update","isAllowed":true},{"type":"delete","isAllowed":true},{"type":"all","isAllowed":true}],"users":["atlas","admin","ambari-qa","holger_gov"],"groups":[],"conditions":[],"delegateAdmin":true}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_atlas/policy/all%20-%20operation -d '{"isEnabled":true,"service":"Sandbox_atlas","name":"all - operation","isAuditEnabled":true,"description":"Policy for all - operation","resources":{"operation":{"values":["*"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"read","isAllowed":true},{"type":"create","isAllowed":true},{"type":"update","isAllowed":true},{"type":"delete","isAllowed":true},{"type":"all","isAllowed":true}],"users":["atlas","admin","ambari-qa","holger_gov"],"groups":[],"conditions":[],"delegateAdmin":true}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_atlas/policy/all%20-%20taxonomy -d '{"isEnabled":true,"service":"Sandbox_atlas","name":"all - taxonomy","isAuditEnabled":true,"description":"Policy for all - taxonomy","resources":{"taxonomy":{"values":["*"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"read","isAllowed":true},{"type":"create","isAllowed":true},{"type":"update","isAllowed":true},{"type":"delete","isAllowed":true},{"type":"all","isAllowed":true}],"users":["atlas","admin","ambari-qa","holger_gov"],"groups":[],"conditions":[],"delegateAdmin":true}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
echo "Updating a sample Ranger policy for the maria_dev"
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_hive/policy/Policy%20for%20raj_ops,holger_gov -d '{"isEnabled":true,"service":"Sandbox_hive","name":"Policy for raj_ops,holger_gov,maria_dev","policyType":0,"description":"","isAuditEnabled":true,"resources":{"column":{"values":["*"],"isExcludes":false,"isRecursive":false},"table":{"values":["*"],"isExcludes":false,"isRecursive":false},"database":{"values":["foodmart"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"all","isAllowed":true}],"users":["raj_ops"],"groups":[],"conditions":[],"delegateAdmin":false},{"accesses":[{"type":"select","isAllowed":true},{"type":"create","isAllowed":true},{"type":"drop","isAllowed":true}],"users":["holger_gov"],"groups":[],"conditions":[],"delegateAdmin":false},{"accesses":[{"type":"select","isAllowed":true}],"users":["maria_dev"],"groups":[],"conditions":[],"delegateAdmin":false}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
echo "Updating a sample Ranger policy for amy_ds"
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin http://$RANGER_HOST:6080/service/public/v2/api/service/Sandbox_hive/policy/Policy%20for%20raj_ops,holger_gov,maria_dev -d '{"isEnabled":true,"service":"Sandbox_hive","name":"Policy for raj_ops,holger_gov,maria_dev and amy_ds","policyType":0,"description":"","isAuditEnabled":true,"resources":{"column":{"values":["*"],"isExcludes":false,"isRecursive":false},"table":{"values":["*"],"isExcludes":false,"isRecursive":false},"database":{"values":["foodmart"],"isExcludes":false,"isRecursive":false}},"policyItems":[{"accesses":[{"type":"all","isAllowed":true}],"users":["raj_ops"],"groups":[],"conditions":[],"delegateAdmin":false},{"accesses":[{"type":"select","isAllowed":true},{"type":"create","isAllowed":true},{"type":"drop","isAllowed":true}],"users":["holger_gov"],"groups":[],"conditions":[],"delegateAdmin":false},{"accesses":[{"type":"select","isAllowed":true}],"users":["maria_dev","amy_ds"],"groups":[],"conditions":[],"delegateAdmin":false}],"denyPolicyItems":[],"allowExceptions":[],"denyExceptions":[],"dataMaskPolicyItems":[],"rowFilterPolicyItems":[]}'
echo "Changing the raj_ops role from User to Admin in Ranger"
curl -u admin:admin -X GET http://$RANGER_HOST:6080/service/xusers/users/userName/raj_ops > /tmp/rajops_id
rajops=$(xmllint --shell /tmp/rajops_id <<< "cat //id/text()" | grep -v "^/ >")
curl -u admin:admin -v -i -s -X PUT -H "Accept: application/json" -H "Content-Type: application/json" http://$RANGER_HOST:6080/service/xusers/secure/users/$rajops -d '{"id":"'"$rajops"'","name":"raj_ops","firstName":"raj_ops","lastName":"raj_ops","description":"raj_ops - add from Unix box","userRoleList":["ROLE_SYS_ADMIN"]}'

